REST-1: POST de tareas
NachOP17/done-rest pull request #16
Opened 2017-12-11 02:51 UTC by douglasdaas

Se agrega trim(quitar el espacio al comienzo y al final) al atributo titulo y descripcion, el post funciona, NOTA: los titulos de las tareas no admiten espacios

2017-12-11 13:49 UTC, cbarroetam requested changes
@douglasdaas  agregar una prueba unitaria para validar este comportamiento

2017-12-15 02:16 UTC, douglasdaas commented
Las pruebas unitarias del post se encuentran en server.test.js

2017-12-15 13:57 UTC, cbarroetam approved these changes

2017-12-15 13:57 UTC, cbarroetam commented
@douglasdaas  por favor resuelve los conflictos sobre este branch y una vez resueltos podemos hacer el merge

2017-12-15 20:02 UTC, merged